[package]
name        = "valence-polytone-utils"
version     = { workspace = true }
edition     = { workspace = true }
authors     = [ "Timewave Labs" ]
description = "Helpers for polytone bridging"

[dependencies]
cosmwasm-std    = { workspace = true }
cosmwasm-schema = { workspace = true }
