[package]
name        = "valence-middleware-utils"
version     = { workspace = true }
edition     = { workspace = true }
authors     = [ "Timewave Labs" ]
description = "valence middleware utilities"

[dependencies]
cosmwasm-std    = { workspace = true }
cosmwasm-schema = { workspace = true }
neutron-sdk     = { workspace = true }
thiserror       = { workspace = true }
prost           = { workspace = true }
semver          = { workspace = true }
