[package]
name       = "valence-middleware-broker"
authors    = { workspace = true }
edition    = { workspace = true }
license    = { workspace = true }
version    = { workspace = true }
repository = { workspace = true }

[lib]
crate-type = [ "cdylib", "rlib" ]

[features]
# use library feature to disable all instantiate/execute/query exports
library = [  ]

[dependencies]
cosmwasm-std             = { workspace = true }
cosmwasm-schema          = { workspace = true }
cw-ownable               = { workspace = true }
prost                    = { workspace = true, features = [ "prost-derive" ] }
prost-types              = { workspace = true }
neutron-sdk              = { workspace = true }
serde-json-wasm          = { version = "1.0.0" }
thiserror                = { workspace = true }
serde_json               = { workspace = true }
cw-storage-plus          = { workspace = true }
valence-middleware-utils = { workspace = true }
semver                   = { workspace = true }
cw2                      = { workspace = true }

[dev-dependencies]
cw-multi-test              = { workspace = true }
valence-middleware-osmosis = { workspace = true }
osmosis-std                = { workspace = true }
osmosis-std-derive         = { workspace = true }
