[noble]
grpc_url  = "http://0.0.0.0"
grpc_port = "57413"
chain_id  = "localnoble-1"
mnemonic  = "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"

[neutron]
grpc_url    = "http://0.0.0.0"
grpc_port   = "57429"
chain_id    = "localneutron-1"
mnemonic    = "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"
target_pool = "neutron1a24zt4ay7mwfp4gurp6yfutrrrvtsf4mhy9h4tpx3642zhscg0ksg5rq7j"
min_ibc_fee = "2000"

[neutron.denoms]
lp_token = "factory/neutron1a24zt4ay7mwfp4gurp6yfutrrrvtsf4mhy9h4tpx3642zhscg0ksg5rq7j/astroport/share"
usdc     = "ibc/65D0BEC6DAD96C7F5043D1E54E54B6BB5D5B3AEC3FF6CEBB75B9E059F3580EA3"
ntrn     = "untrn"

[neutron.accounts]
deposit     = "neutron1y9al39hhn3r04enmkhqcefcep4y0d20cgdhncmlf0dyj3dagwzws69vnfz"
position    = "neutron17qwj7l6wp5ax9ek8azs7x2l6m9m9la87fvw8zjrylv0t0u32zxzqdf63wg"
withdraw    = "neutron1l7cudn7y2pw4909kt08lrw9y87lcsvwn6pf0jp0mtd3un6km5t3qlpsnkp"
liquidation = "neutron1dk6wun3380u8xrw7dn2gmd4dsldxhzgy98u7qn2tts2jr3s8r9jsep5qj2"

[neutron.accounts.noble_inbound_ica]
library_account = "neutron1yp9pyhhx6c3ryhq082wng6myh0fd3m608k3r8lt0e5hv6ted9rtsga2lkh"
remote_addr     = "noble1gy9w6u7gw0rfkuwp6gmnaczahzsl60mpk80me6ezwq00zk9th8fsngmkx2"

[neutron.accounts.noble_outbound_ica]
library_account = "neutron17y5ggatzz6n84tgvmnzt5ywqsfu6nl04vjgq6jqxy276vy2qrrtstvgwx7"
remote_addr     = "noble1v235yhtldjl2cpqndvsg290lnq25hxwaevfsc6rrzht05ltk2txqpeum7g"

[neutron.libraries]
neutron_ibc_transfer   = "neutron1q78fcz4ngcd4rfylzzp4t0cr3r4ckrvk9f99nm4zghseht4urpnqc4z2gj"
noble_inbound_transfer = "neutron1qvfrfky5w9z634dmhn0pxre0crr7me56rwn97nlqdkhjsnzh2l2q5t2y06"
noble_cctp_transfer    = "neutron1mld746gpzfruhdxc9n4qljtf967m4tzm39scc5rs2pda7n4eanuq9m0lvg"
astroport_lper         = "neutron1sz3hzfssxgks0edg3uu6c6hpmqad4rhg5c569vcq54rcxpa825ssrac7q9"
astroport_lwer         = "neutron1q6f0xezc7u02d486tutly5389p3sjfd5mdqx79fwgp7qhwgqxcus83d4zt"
liquidation_forwarder  = "neutron1jr9qyvda4jhyh3u5k79vt3y203xcyufjxfkplfkm2ys958ad7xsswehlm5"
authorizations         = "neutron1qgeh2yg7m54t5k7szq6zums8ays7e82vmu33gcgxjuszhxjqswrqzchqdu"
processor              = "neutron1kl4f3rw7qre22v3usqmcl5vusk4ch6xrxp2s4nt7cgsfl4788ajssghpug"

[ethereum]
rpc_url  = "http://localhost:8545"
mnemonic = "test test test test test test test test test test test junk"

[ethereum.denoms]
usdc_erc20 = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"

[ethereum.accounts]
deposit  = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
withdraw = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"

[ethereum.libraries]
valence_vault  = "0x9A676e781A523b5d0C0e43731313A708CB607508"
cctp_forwarder = "0x610178dA211FEF7D417bC0e6FeD39F05609AD788"
lite_processor = "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0"
