[package]
name = "valence-magma-utils"
version     = { workspace = true }
edition     = { workspace = true }
authors     = { workspace = true }
description = "Helpers for duality integrations"

[dependencies]
cosmwasm-std    = { workspace = true }
cosmwasm-schema = { workspace = true }
serde           = { workspace = true }
schemars        = { workspace = true }
serde_json      = { workspace = true }