[chains]

[chains.cosmos-hub]
name      = "cosmos-hub"
rpc       = "https://rpc.cosmos.network:443"
grpc      = "https://cosmos-testnet-grpc.polkachu.com:14990"
prefix    = "cosmos"
gas_price = "0.025"
gas_denom = "uatom"
coin_type = "118"
coin_type2 = "118"

[chains.neutron]
name      = "neutron"
rpc       = "https://rpc.cosmos.network:443"
grpc      = "https://neutron-testnet-grpc.polkachu.com:19190"
prefix    = "neutron"
gas_price = "0.075"
gas_denom = "uatom"
coin_type = "118"
