[package]
name        = "valence-authorization-utils"
version     = { workspace = true }
edition     = { workspace = true }
authors     = ["Timewave Labs"]
description = "Helpers for authorization contract"

[dependencies]
cosmwasm-std            = { workspace = true }
cw-utils                = { workspace = true }
cosmwasm-schema         = { workspace = true }
neutron-sdk             = { workspace = true }
