[package]
name        = "valence-authorization-utils"
version     = { workspace = true }
edition     = { workspace = true }
authors     = { workspace = true }
description = "Helpers for authorization contract"

[dependencies]
ark-bn254             = { workspace = true }
ark-groth16           = { workspace = true }
ark-serialize         = { workspace = true }
cosmwasm-std          = { workspace = true }
cw-utils              = { workspace = true }
cosmwasm-schema       = { workspace = true }
cw-ownable            = { workspace = true }
valence-gmp-utils     = { workspace = true }
valence-library-utils = { workspace = true }
serde_json            = { workspace = true }
