[package]
name        = "valence-macros"
version     = { workspace = true }
edition     = { workspace = true }
authors     = [ "Timewave Labs" ]
description = "Macros for Valence libraries and accounts"
license     = { workspace = true }

[lib]
proc-macro = true

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
proc-macro2     = "1.0"
quote           = "1.0"
syn             = { version = "2.0", features = [ "full", "parsing", "extra-traits" ] }
