[book]
authors      = [ "Timewave Labs" ]
language     = "en"
multilingual = false
src          = "src"
title        = "Valence Protocol Documentation"

[output.html]
git-repository-url    = "https://github.com/timewave-computer/valence-protocol"
default-theme         = "light"
preferred-light-theme = "light"
preferred-dark-theme  = "ayu"
additional-js         = [ "mermaid.min.js", "mermaid-init.js" ]
mathjax-support       = true

[preprocessor.mermaid]
command = "mdbook-mermaid"
